/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.80
 * Generated at: 2023-11-28 10:27:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.user;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/lee/tour_workspace/spring_final_project-main/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/_spring_final_project/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1698676865210L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp", out, false);
      out.write("\r\n");
      out.write("		\r\n");
      out.write("			<form action=\"/user/join\" method=\"post\" onsubmit=\"return validation()\">\r\n");
      out.write("				<div class=\"inner-container\">\r\n");
      out.write("					<div>\r\n");
      out.write("						<h1>회원가입</h1>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"title\">아이디<span class=\"required\">*</span></div>\r\n");
      out.write("						<div class=\"input-box id-input\"><input type=\"text\" id=\"id\" name=\"id\" autocomplete=\"off\" placeholder=\"아이디를 입력하세요(영문+숫자 4자~8자)\"><button id=\"checkId\" type=\"button\" disabled>중복확인</button></div>\r\n");
      out.write("						<div class=\"id-check\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"title\">비밀번호<span class=\"required\">*</span></div>\r\n");
      out.write("						<div class=\"input-box\"><input type=\"password\" id=\"pwd\" name=\"pwd\" autocomplete=\"off\" placeholder=\"비밀번호를 입력하세요(4자~8자)\"></div>\r\n");
      out.write("						<div class=\"pwd-check\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"title\">비밀번호확인<span class=\"required\">*</span></div>\r\n");
      out.write("						<div class=\"input-box\"><input type=\"password\" id=\"pwd2\" name=\"pwd2\" autocomplete=\"off\" placeholder=\"비밀번호를 재입력하세요.\"></div>\r\n");
      out.write("						<div class=\"pwd-check2\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"title\">이름<span class=\"required\">*</span></div>\r\n");
      out.write("						<div class=\"input-box\"><input type=\"text\" id=\"name\" name=\"name\" autocomplete=\"off\" placeholder=\"이름을 입력하세요.\"></div>\r\n");
      out.write("						<div class=\"name-check\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"title\">나이<span class=\"required\">*</span></div>\r\n");
      out.write("						<div class=\"input-box\"><input id=\"age\" type=\"text\" name=\"age\" placeholder=\"나이를 입력하세요(숫자)\"></div>\r\n");
      out.write("						<div class=\"age-check\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"title\">연락처<span class=\"required\">*</span></div>\r\n");
      out.write("						<div class=\"input-box\"><input type=\"text\" id=\"phone\" name=\"phoneNumber\" autocomplete=\"off\" placeholder=\"연락처를 입력하세요(' - ' 제외 10자리~12자리)\"></div>\r\n");
      out.write("						<div class=\"phone-check\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"title\">이메일<span class=\"required\">*</span></div>\r\n");
      out.write("						<div class=\"input-box email-box\">\r\n");
      out.write("							<input type=\"text\" id=\"firstEmail\" placeholder=\"이메일\">@<input type=\"text\" id=\"lastEmail\" placeholder=\"직접입력\">\r\n");
      out.write("							<input type=\"hidden\" id=\"email\" name=\"email\">\r\n");
      out.write("							<select id=\"emailSelect\" name=\"select\">\r\n");
      out.write("								<option value=\"\">직접입력\r\n");
      out.write("								<option value=\"google.com\">google.com\r\n");
      out.write("								<option value=\"naver.com\">naver.com\r\n");
      out.write("								<option value=\"nate.com\">nate.com\r\n");
      out.write("								<option value=\"hotmail.com\">hotmail.com\r\n");
      out.write("							</select>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"email-check\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div>\r\n");
      out.write("						<div class=\"title\">주소</div>\r\n");
      out.write("						<div class=\"input-box\"><input type=\"text\" id=\"address\" name=\"address\" autocomplete=\"off\" placeholder=\"주소를 입력하세요.\"></div>\r\n");
      out.write("						<div class=\"address-check\"></div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"button-box\">\r\n");
      out.write("						<span><a href=\"/\"><button type=\"button\">취소</button></a></span>\r\n");
      out.write("						<span><button type=\"\" class=\"join-btn\">확인</button></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</form>\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script type=\"text/javascript\" src=\"/resources/js/user.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("	let msg = `");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("`;\r\n");
      out.write("	if(msg == 2){\r\n");
      out.write("		alert('비밀번호를 입력해 주세요.');\r\n");
      out.write("	} else if(msg == 3){\r\n");
      out.write("		alert('이미 존재하는 ID 입니다.')\r\n");
      out.write("	} else if(msg == 4){\r\n");
      out.write("		alert(\"필수 항목을 입력해 주세요.\")\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/user/join.jsp(81,12) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }
}
